from datetime import datetime, timezone
from sqlalchemy.orm import Session
from .models import Artifact, Sentiment, Projection, Relationship

SEED_ARTIFACTS = [
    # ── Books ──────────────────────────────────────────────────────────────
    {
        "title": "Superintelligence: Paths, Dangers, Strategies",
        "artifact_type": "book", "author": "Nick Bostrom",
        "url": "https://global.oup.com/academic/product/superintelligence-9780199678112",
        "date_published": datetime(2014, 9, 3, tzinfo=timezone.utc),
        "description": "Seminal work exploring how superintelligence could be created and what risks it poses. Introduces orthogonality thesis, instrumental convergence, and the concept of the AI control problem.",
        "tags": "superintelligence,safety,alignment,risks,orthogonality,instrumental-convergence",
        "sentiments": [{"score": -0.3, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "cautionary", "confidence": 0.85, "timeframe": "2040-2060", "summary": "Superintelligence poses existential risks if not aligned with human values"}],
    },
    {
        "title": "The Singularity Is Near",
        "artifact_type": "book", "author": "Ray Kurzweil",
        "url": "https://www.penguinrandomhouse.com/books/176126/the-singularity-is-near-by-ray-kurzweil/",
        "date_published": datetime(2005, 9, 26, tzinfo=timezone.utc),
        "description": "Predicts the technological singularity by 2045, where AI surpasses human intelligence and triggers runaway technological growth, leading to radical life extension and abundance.",
        "tags": "singularity,accelerationist,transhumanism,exponential-growth",
        "sentiments": [{"score": 0.8, "label": "very_positive", "source": "initial"}],
        "projections": [{"projection_type": "utopian", "confidence": 0.9, "timeframe": "2045", "summary": "Singularity by 2045 leading to radical life extension and material abundance"}],
    },
    {
        "title": "Life 3.0: Being Human in the Age of Artificial Intelligence",
        "artifact_type": "book", "author": "Max Tegmark",
        "url": "https://www.penguinrandomhouse.com/books/530772/life-30-by-max-tegmark/",
        "date_published": datetime(2017, 8, 29, tzinfo=timezone.utc),
        "description": "Explores possible futures after AGI, organizing them into scenarios from libertarian utopia to authoritarian surveillance to human extinction. Discusses the physical limits of intelligence and AI governance.",
        "tags": "futures,governance,scenarios,ai-safety,cosmology",
        "sentiments": [{"score": 0.1, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.6, "timeframe": "2050", "summary": "Multiple possible futures; outcome depends on choices we make today"}],
    },
    {
        "title": "Human Compatible: Artificial Intelligence and the Problem of Control",
        "artifact_type": "book", "author": "Stuart Russell",
        "url": "https://www.penguinrandomhouse.com/books/566677/human-compatible-by-stuart-russell/",
        "date_published": datetime(2019, 10, 8, tzinfo=timezone.utc),
        "description": "Argues that the standard AI model of optimizing a fixed objective is fundamentally flawed. Proposes a new framework where machines are uncertain about human preferences and must learn them through observation.",
        "tags": "alignment,control-problem,preference-uncertainty,provably-beneficial",
        "sentiments": [{"score": 0.2, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "cautionary", "confidence": 0.75, "timeframe": "2030-2050", "summary": "AI control problem is solvable but requires fundamental rethinking of AI objectives"}],
    },
    {
        "title": "The Alignment Problem: Machine Learning and Human Values",
        "artifact_type": "book", "author": "Brian Christian",
        "url": "https://wwnorton.com/books/9780393635829",
        "date_published": datetime(2020, 10, 6, tzinfo=timezone.utc),
        "description": "Accessible overview tracing the alignment problem through reinforcement learning, inverse reinforcement learning, and the practical challenges of specifying human values in AI systems.",
        "tags": "alignment,safety,ethics,overview,history",
        "sentiments": [{"score": -0.1, "label": "neutral", "source": "initial"}],
    },
    {
        "title": "AI 2041: Ten Visions for Our Future",
        "artifact_type": "book", "author": "Kai-Fu Lee and Chen Qiufan",
        "url": "https://www.penguinrandomhouse.com/books/672421/ai-2041-by-kai-fu-lee-and-chen-qiufan/",
        "date_published": datetime(2021, 9, 14, tzinfo=timezone.utc),
        "description": "Ten fictional stories set in 2041 each paired with an analytical essay, exploring how AI might reshape work, education, healthcare, and geopolitics across different cultural contexts.",
        "tags": "futures,fiction,scenarios,geopolitics,work",
        "sentiments": [{"score": 0.3, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.5, "timeframe": "2041", "summary": "AI transforms every aspect of life by 2041; outcomes vary widely by region and policy"}],
    },
    {
        "title": "The Precipice: Existential Risk and the Future of Humanity",
        "artifact_type": "book", "author": "Toby Ord",
        "url": "https://theprecipice.com/",
        "date_published": datetime(2020, 3, 24, tzinfo=timezone.utc),
        "description": "Quantitative analysis of existential risks facing humanity, ranking unaligned AI as the most severe risk. Argues we are in a 'precipice' moment where humanity's long-term potential hangs in the balance.",
        "tags": "existential-risk,xrisk,longtermism,global-priorities",
        "sentiments": [{"score": -0.5, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "cautionary", "confidence": 0.8, "timeframe": "2020-2100", "summary": "Unaligned AI is the #1 existential risk; we are in a uniquely precarious century"}],
    },
    {
        "title": "Our Final Invention: Artificial Intelligence and the End of the Human Era",
        "artifact_type": "book", "author": "James Barrat",
        "url": "https://www.penguinrandomhouse.com/books/226939/our-final-invention-by-james-barrat/",
        "date_published": datetime(2013, 10, 1, tzinfo=timezone.utc),
        "description": "Examines the risks of creating artificial general intelligence without adequate safety precautions, arguing that AGI could be humanity's 'final invention' if not handled carefully.",
        "tags": "risks,safety,extinction,superintelligence",
        "sentiments": [{"score": -0.7, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "dystopian", "confidence": 0.7, "timeframe": "2030-2050", "summary": "AGI likely leads to human displacement or extinction without drastic safety measures"}],
    },
    {
        "title": "Scary Smart: The Future of Artificial Intelligence and How You Can Save Our World",
        "artifact_type": "book", "author": "Mo Gawdat",
        "url": "https://www.panmacmillan.com/authors/mo-gawdat/scary-smart/9781529061617",
        "date_published": datetime(2021, 9, 16, tzinfo=timezone.utc),
        "description": "Former Google X executive argues that AI is on an exponential trajectory and will inevitably surpass human intelligence, urging a values-first approach to technology development.",
        "tags": "exponential,ethics,values,governance,public",
        "sentiments": [{"score": -0.2, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "cautionary", "confidence": 0.65, "timeframe": "2030-2040", "summary": "AI inevitability is high; we must embed values into systems now"}],
    },
    {
        "title": "Genius Makers: The Mavericks Who Brought AI to Google, Facebook, and the World",
        "artifact_type": "book", "author": "Cade Metz",
        "url": "https://www.penguinrandomhouse.com/books/622340/genius-makers-by-cade-metz/",
        "date_published": datetime(2021, 3, 16, tzinfo=timezone.utc),
        "description": "Journalistic account of the people who drove the deep learning revolution, from Geoffrey Hinton's lonely crusade to the founding of DeepMind, OpenAI, and the modern AI industry.",
        "tags": "history,deep-learning,dnn,people,hinton",
        "sentiments": [{"score": 0.4, "label": "positive", "source": "initial"}],
    },
    # ── Key Papers ──────────────────────────────────────────────────────────
    {
        "title": "GPT-4 Technical Report",
        "artifact_type": "paper", "author": "OpenAI",
        "url": "https://arxiv.org/abs/2303.08774",
        "date_published": datetime(2023, 3, 15, tzinfo=timezone.utc),
        "description": "Technical report detailing GPT-4, a large multimodal model exhibiting human-level performance on professional benchmarks including the bar exam and AP tests.",
        "tags": "llm,transformer,scaling,benchmarks,multimodal",
        "sentiments": [{"score": 0.6, "label": "positive", "source": "initial"}],
    },
    {
        "title": "Scaling Laws for Neural Language Models",
        "artifact_type": "paper", "author": "Jared Kaplan, Sam McCandlish, Tom Henighan, et al.",
        "url": "https://arxiv.org/abs/2001.08361",
        "date_published": datetime(2020, 1, 23, tzinfo=timezone.utc),
        "description": "Empirical study showing that language model performance follows smooth power-law scaling with compute, dataset size, and model size. Foundational paper for the scaling hypothesis that drives frontier AI.",
        "tags": "scaling-laws,compute,power-law,foundational",
        "sentiments": [{"score": 0.5, "label": "positive", "source": "initial"}],
    },
    {
        "title": "Training Compute-Optimal Large Language Models (Chinchilla)",
        "artifact_type": "paper", "author": "Jordan Hoffmann, Sebastian Borgeaud, et al.",
        "url": "https://arxiv.org/abs/2203.15556",
        "date_published": datetime(2022, 3, 29, tzinfo=timezone.utc),
        "description": "Shows that most LLMs are significantly undertrained. Introduces Chinchilla, a 70B parameter model trained on much more data than typical, achieving state-of-the-art performance.",
        "tags": "scaling-laws,data,training-optimality,chinchilla",
        "sentiments": [{"score": 0.5, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "accelerationist", "confidence": 0.7, "timeframe": "2022-2025", "summary": "Scaling compute-optimal models accelerates capability trajectory"}],
    },
    {
        "title": "Constitutional AI: Harmlessness from AI Feedback",
        "artifact_type": "paper", "author": "Yuntao Bai, Saurav Kadavath, et al. (Anthropic)",
        "url": "https://arxiv.org/abs/2212.08073",
        "date_published": datetime(2022, 12, 15, tzinfo=timezone.utc),
        "description": "Introduces Constitutional AI, a method for training helpful and harmless AI assistants using a set of ethical principles and AI-generated feedback rather than pure human labels.",
        "tags": "alignment,rlhf,constitutional-ai,harmlessness,anthropic",
        "sentiments": [{"score": 0.6, "label": "positive", "source": "initial"}],
    },
    {
        "title": "Weak-to-Strong Generalization: Eliciting the Capabilities of Weakly Supervised LLMs",
        "artifact_type": "paper", "author": "Samuel R. Bowman, et al. (OpenAI)",
        "url": "https://arxiv.org/abs/2312.09390",
        "date_published": datetime(2023, 12, 14, tzinfo=timezone.utc),
        "description": "Explores whether weak supervisors (humans) can effectively supervise strong (superhuman) models. Finds promising evidence that strong models can generalize beyond their weak supervision, with implications for scalable oversight.",
        "tags": "superalignment,scalable-oversight,weak-to-strong,openai",
        "sentiments": [{"score": 0.3, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.55, "timeframe": "2024-2030", "summary": "Weak-to-strong generalization is promising but insufficient; more research needed for robust scalable oversight"}],
    },
    {
        "title": "Direct Preference Optimization: Your Language Model is Secretly a Reward Model",
        "artifact_type": "paper", "author": "Rafael Rafailov, Archit Sharma, Eric Mitchell, et al.",
        "url": "https://arxiv.org/abs/2305.18290",
        "date_published": datetime(2023, 5, 29, tzinfo=timezone.utc),
        "description": "DPO reformulates RLHF without explicit reward modeling, directly optimizing from human preferences. Becomes a widely adopted alignment technique due to its simplicity and effectiveness.",
        "tags": "alignment,dpo,rlhf,preference-optimization",
        "sentiments": [{"score": 0.5, "label": "positive", "source": "initial"}],
    },
    {
        "title": "Tree of Thoughts: Deliberate Problem Solving with Large Language Models",
        "artifact_type": "paper", "author": "Shunyu Yao, Dian Yu, Jeffrey Zhao, et al.",
        "url": "https://arxiv.org/abs/2305.10601",
        "date_published": datetime(2023, 5, 18, tzinfo=timezone.utc),
        "description": "Proposes Tree of Thoughts (ToT), which enables LLMs to explore multiple reasoning paths and look ahead/backtrack, dramatically improving performance on tasks requiring planning and search.",
        "tags": "reasoning,planning,problem-solving,llm-capabilities",
        "sentiments": [{"score": 0.4, "label": "positive", "source": "initial"}],
    },
    {
        "title": "Mechanistic Interpretability for AI Safety — A Review",
        "artifact_type": "paper", "author": "Leonard Bereska, Efstratios Gavves",
        "url": "https://arxiv.org/abs/2404.14082",
        "date_published": datetime(2024, 4, 22, tzinfo=timezone.utc),
        "description": "Comprehensive survey of mechanistic interpretability methods including sparse autoencoders, activation patching, and circuit discovery. Assesses relevance of MI to AI safety and alignment.",
        "tags": "interpretability,mechanistic-interpretability,survey,safety",
        "sentiments": [{"score": 0.4, "label": "positive", "source": "initial"}],
    },
    # ── Essays ─────────────────────────────────────────────────────────────
    {
        "title": "AGI Ruin: A List of Lethalities",
        "artifact_type": "essay", "author": "Eliezer Yudkowsky",
        "url": "https://www.lesswrong.com/posts/uMQ3cqWDPHhjtiesc/agi-ruin-a-list-of-lethalities",
        "date_published": datetime(2022, 5, 1, tzinfo=timezone.utc),
        "description": "Argues that alignment of superhuman AGI is extremely difficult and humanity is not on track to solve it. The 'default outcome' is catastrophic — human extinction.",
        "tags": "alignment,xrisk,safety,doom,yudkowsky",
        "sentiments": [{"score": -0.9, "label": "very_negative", "source": "initial"}],
        "projections": [{"projection_type": "dystopian", "confidence": 0.95, "timeframe": "2030-2040", "summary": "Default outcome of AGI development is human extinction; alignment is severely harder than capabilities"}],
    },
    {
        "title": "Situational Awareness: The Decade Ahead",
        "artifact_type": "essay", "author": "Leopold Aschenbrenner",
        "url": "https://situational-awareness.ai/",
        "date_published": datetime(2024, 6, 1, tzinfo=timezone.utc),
        "description": "Argues transformative AI is likely by 2027-2030, exploring the sharp left turn in AI capabilities, the geopolitical race between US and China, and the economic implications of automated AI R&D.",
        "tags": "takeoff,transformation,geopolitics,scaling,us-china",
        "sentiments": [{"score": 0.2, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "accelerationist", "confidence": 0.8, "timeframe": "2027-2030", "summary": "Transformative AGI within 3-5 years; massive economic and geopolitical shifts; automated AI R&D"}],
    },
    {
        "title": "What Matters Most: AGI and Human Flourishing",
        "artifact_type": "essay", "author": "Sam Altman",
        "url": "https://blog.samaltman.com/what-matters-most",
        "date_published": datetime(2025, 1, 15, tzinfo=timezone.utc),
        "description": "Altman's personal vision for AGI as the most powerful technology ever created, emphasizing broad distribution of benefits, careful stewardship, and iterative deployment.",
        "tags": "agi,optimism,governance,openai,flourishing",
        "sentiments": [{"score": 0.7, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "utopian", "confidence": 0.7, "timeframe": "2030-2035", "summary": "AGI will amplify human capabilities and create unprecedented prosperity if stewarded well"}],
    },
    {
        "title": "The Bitter Lesson",
        "artifact_type": "essay", "author": "Rich Sutton",
        "url": "http://www.incompleteideas.net/IncIdeas/BitterLesson.html",
        "date_published": datetime(2019, 3, 13, tzinfo=timezone.utc),
        "description": "Argues that the biggest lesson from AI research is that general methods that leverage computation ultimately prevail over human-engineered domain knowledge. Foundational essay for the scaling paradigm.",
        "tags": "scaling,computation,general-methods,bitter-lesson",
        "sentiments": [{"score": 0.6, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "accelerationist", "confidence": 0.85, "timeframe": "2019-2030", "summary": "Scaling computation will continue to drive AI advances; general methods will dominate"}],
    },
    {
        "title": "Meditations on Moloch",
        "artifact_type": "essay", "author": "Scott Alexander",
        "url": "https://slatestarcodex.com/2014/07/30/meditations-on-moloch/",
        "date_published": datetime(2014, 7, 30, tzinfo=timezone.utc),
        "description": "Explores how competitive dynamics (Moloch) trap humanity into collectively undesirable outcomes. Applied to AI: the race dynamics of AI development may force unsafe acceleration.",
        "tags": "moloch,race-dynamics,coordination,traps,philosophy",
        "sentiments": [{"score": -0.6, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "dystopian", "confidence": 0.7, "timeframe": "2020-2050", "summary": "Competitive AI race dynamics may force unsafe development regardless of individual actors' preferences"}],
    },
    {
        "title": "Draft Report on AI Timelines",
        "artifact_type": "essay", "author": "Ajeya Cotra",
        "url": "https://www.alignmentforum.org/posts/KrJfoZzpSDpnrv9va/draft-report-on-ai-timelines",
        "date_published": datetime(2020, 5, 17, tzinfo=timezone.utc),
        "description": "Pioneering 'bio anchors' forecasting methodology for AGI timelines, anchoring on when AI systems can automate AI research itself. Median estimate: transformative AI around 2050 with wide uncertainty.",
        "tags": "timelines,forecasting,bio-anchors,methodology",
        "sentiments": [{"score": 0.0, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.7, "timeframe": "2050", "summary": "Transformative AI median around 2050 with wide uncertainty (2025-2090)"}],
    },
    {
        "title": "Machines of Loving Grace: How AI Could Transform the World for the Better",
        "artifact_type": "essay", "author": "Dario Amodei",
        "url": "https://darioamodei.com/machines-of-loving-grace",
        "date_published": datetime(2024, 10, 11, tzinfo=timezone.utc),
        "description": "Anthropic CEO's vision of a 'compressed 21st century' where powerful AI compresses centuries of scientific progress into 5-10 years. Explores potential breakthroughs in biology, neuroscience, and economic development.",
        "tags": "compressed-century,biology,neuroscience,development,anthropic",
        "sentiments": [{"score": 0.8, "label": "very_positive", "source": "initial"}],
        "projections": [{"projection_type": "utopian", "confidence": 0.75, "timeframe": "2026-2036", "summary": "Powerful AI compresses 100 years of scientific progress into a decade; radical advances in health, brain science, and human flourishing"}],
    },
    # ── Tweets ──────────────────────────────────────────────────────────────
    {
        "title": "Sam Altman: 'AGI will be the most powerful technology humanity has ever built'",
        "artifact_type": "tweet", "author": "samaltman",
        "url": "https://nitter.net/samaltman",
        "date_published": datetime(2025, 1, 16, tzinfo=timezone.utc),
        "description": "Sam Altman on AGI as the most powerful technology ever created, emphasizing the importance of putting it in the hands of everyone and building the institutions to govern it wisely.",
        "tags": "openai,altman,agi,governance,democratization",
        "sentiments": [{"score": 0.7, "label": "positive", "source": "initial"}],
    },
    {
        "title": "Elon Musk: 'There is some probability that AI kills humans. I think it's low, but non-trivial — maybe 10-20%'",
        "artifact_type": "tweet", "author": "elonmusk",
        "url": "https://nitter.net/elonmusk",
        "date_published": datetime(2024, 4, 1, tzinfo=timezone.utc),
        "description": "Elon Musk estimates 10-20% chance of AGI leading to catastrophic outcomes, stressing the importance of caution and the need for AI regulation.",
        "tags": "risk-assessment,timelines,xai,musk",
        "sentiments": [{"score": -0.3, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "cautionary", "confidence": 0.5, "timeframe": "2030-2040", "summary": "10-20% chance of catastrophic AI outcomes; non-trivial risk warrants precaution"}],
    },
    {
        "title": "Yann LeCun: 'AGI is nowhere near imminent — we lack fundamental understanding'",
        "artifact_type": "tweet", "author": "ylecun",
        "url": "https://nitter.net/ylecun",
        "date_published": datetime(2024, 9, 15, tzinfo=timezone.utc),
        "description": "Meta AI Chief Yann LeCun argues that AGI is not imminent, that current LLMs lack crucial capabilities (understanding, planning, reasoning), and that hype is dangerous.",
        "tags": "timelines,skepticism,understanding,limitations,lecun",
        "sentiments": [{"score": -0.1, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.6, "timeframe": "2050+", "summary": "AGI far off; current approaches are insufficient; deep learning needs fundamental breakthroughs"}],
    },
    {
        "title": "Demis Hassabis: 'I think we could achieve AGI within the next decade'",
        "artifact_type": "tweet", "author": "demishassabis",
        "url": "https://nitter.net/demishassabis",
        "date_published": datetime(2024, 6, 12, tzinfo=timezone.utc),
        "description": "DeepMind CEO Demis Hassabis states AGI could be achieved within a decade, emphasizing DeepMind's focus on safety alongside capabilities.",
        "tags": "deepmind,timelines,agi,safety,hassabis",
        "sentiments": [{"score": 0.2, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "accelerationist", "confidence": 0.65, "timeframe": "2028-2034", "summary": "AGI achievable within a decade; DeepMind prioritizing safety research alongside capabilities"}],
    },
    {
        "title": "Andrej Karpathy: 'The neural network training process is becoming the new programming'",
        "artifact_type": "tweet", "author": "karpathy",
        "url": "https://nitter.net/karpathy",
        "date_published": datetime(2024, 3, 20, tzinfo=timezone.utc),
        "description": "Andrej Karpathy on how training neural networks is replacing traditional programming; 'Software 2.0' where data and compute replace explicit code.",
        "tags": "software-2,training,programming-paradigm,karpathy",
        "sentiments": [{"score": 0.5, "label": "positive", "source": "initial"}],
    },
    {
        "title": "Shane Legg: 'AGI is likely by 2028 — it's the most important event in human history'",
        "artifact_type": "tweet", "author": "shanelegg",
        "url": "https://nitter.net/shanelegg",
        "date_published": datetime(2024, 11, 1, tzinfo=timezone.utc),
        "description": "DeepMind co-founder and chief AGI scientist Shane Legg reiterates his long-standing prediction that AGI is likely by 2028 and that it's the most important transition humanity will face.",
        "tags": "deepmind,timelines,legg,agi,forecast",
        "sentiments": [{"score": 0.3, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "accelerationist", "confidence": 0.7, "timeframe": "2028", "summary": "AGI by 2028; most important event in human history requiring preparation now"}],
    },
    {
        "title": "Geoffrey Hinton: 'I'm now a pessimist on AI — we're not moving fast enough on safety'",
        "artifact_type": "tweet", "author": "geoffreyhinton",
        "url": "https://nitter.net/geoffreyhinton",
        "date_published": datetime(2024, 5, 13, tzinfo=timezone.utc),
        "description": "Godfather of AI Geoffrey Hinton expresses growing pessimism about AI safety, saying the field is not moving fast enough and that existential risk from AI is a real possibility.",
        "tags": "hinton,pessimism,safety,existential-risk",
        "sentiments": [{"score": -0.6, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "cautionary", "confidence": 0.7, "timeframe": "2024-2040", "summary": "AI safety efforts insufficient; existential risk is real and we need to move faster"}],
    },
    # ── Interviews ──────────────────────────────────────────────────────────
    {
        "title": "Lex Fridman Podcast: Sam Altman on AGI, Open Source, and the Future",
        "artifact_type": "interview", "author": "Sam Altman / Lex Fridman",
        "url": "https://lexfridman.com/sam-altman-2/",
        "date_published": datetime(2025, 2, 20, tzinfo=timezone.utc),
        "description": "Wide-ranging discussion on OpenAI's path to AGI, the importance of iterative deployment, open vs closed source debate, and what post-AGI society might look like.",
        "tags": "openai,altman,lex-fridman,agi,governance",
        "sentiments": [{"score": 0.3, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "utopian", "confidence": 0.6, "timeframe": "2030", "summary": "Iterative deployment path to AGI with broad benefit distribution"}],
    },
    {
        "title": "Lex Fridman Podcast: Yann LeCun on AGI, Vision, and the Path Forward",
        "artifact_type": "interview", "author": "Yann LeCun / Lex Fridman",
        "url": "https://lexfridman.com/yann-lecun-2/",
        "date_published": datetime(2024, 7, 10, tzinfo=timezone.utc),
        "description": "Yann LeCun argues that current AI is far from AGI, that objective-driven AI and world models are needed, and that the concern about AI risk is overblown compared to other existential threats.",
        "tags": "skepticism,world-models,objectives,lecun,lex-fridman",
        "sentiments": [{"score": 0.2, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.55, "timeframe": "2040-2060", "summary": "AGI far off and overhyped; world models and objective-driven architectures needed"}],
    },
    {
        "title": "80,000 Hours: Ajeya Cotra on AI Timelines and Bio Anchors",
        "artifact_type": "interview", "author": "Ajeya Cotra / 80,000 Hours",
        "url": "https://80000hours.org/podcast/episodes/ajeya-cotra-ai-timelines-precautions/",
        "date_published": datetime(2021, 7, 13, tzinfo=timezone.utc),
        "description": "Cotra explains the bio anchors framework, why transformative AI might arrive around 2050, and what precautions humanity should take now.",
        "tags": "timelines,forecasting,bio-anchors,xrisk,80000-hours",
        "sentiments": [{"score": 0.1, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.65, "timeframe": "2050", "summary": "Transformative AI median 2050; wide uncertainty range; bio anchors framework"}],
    },
    {
        "title": "Joe Rogan Experience: Roman Yampolskiy on AI Safety and Superintelligence",
        "artifact_type": "interview", "author": "Roman Yampolskiy / Joe Rogan",
        "url": "https://www.youtube.com/watch?v=j2i9D24KQ5k",
        "date_published": datetime(2025, 9, 24, tzinfo=timezone.utc),
        "description": "AI safety researcher Roman Yampolskiy discusses why AI safety is fundamentally unsolved, the impossibility guarantees, and why superintelligence may be uncontrollable by definition.",
        "tags": "safety,uncontrollability,jre,yampolskiy,impossibility",
        "sentiments": [{"score": -0.7, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "dystopian", "confidence": 0.85, "timeframe": "2030-2050", "summary": "Superintelligence may be fundamentally uncontrollable; safety guarantees are impossible"}],
    },
    {
        "title": "Debate: AGI Timelines — Short vs Long",
        "artifact_type": "interview", "author": "Dwarkesh Patel / Various",
        "url": "https://www.dwarkeshpatel.com/",
        "date_published": datetime(2024, 8, 1, tzinfo=timezone.utc),
        "description": "Series of podcast debates between AI researchers on AGI timelines. Short-timeline believers (2027-2030) vs long-timeline skeptics (2050+), featuring diverse perspectives from leading researchers.",
        "tags": "timelines,debate,forecasting,podcast",
        "sentiments": [{"score": 0.0, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.5, "timeframe": "2027-2050", "summary": "Wide disagreement reflecting deep uncertainty about the pace of AI progress"}],
    },
    # ── News ────────────────────────────────────────────────────────────────
    {
        "title": "DeepMind's AlphaFold and AI-Driven Scientific Discovery",
        "artifact_type": "news", "author": "DeepMind",
        "url": "https://deepmind.google/alphafold/",
        "date_published": datetime(2024, 5, 8, tzinfo=timezone.utc),
        "description": "AlphaFold 3 predicts joint structures of proteins and other biomolecules, accelerating drug discovery. Represents AI's growing role as a tool for fundamental scientific breakthroughs.",
        "tags": "science,drug-discovery,ai-capabilities,alphafold",
        "sentiments": [{"score": 0.8, "label": "very_positive", "source": "initial"}],
    },
    {
        "title": "Open Letter: Pause Giant AI Experiments",
        "artifact_type": "news", "author": "Future of Life Institute",
        "url": "https://futureoflife.org/open-letter/pause-giant-ai-experiments/",
        "date_published": datetime(2023, 3, 22, tzinfo=timezone.utc),
        "description": "Open letter signed by thousands of researchers and figures including Elon Musk, Steve Wozniak, and Yoshua Bengio, calling for a 6-month pause on training AI systems more powerful than GPT-4.",
        "tags": "governance,safety,pause,regulation,open-letter",
        "sentiments": [{"score": -0.4, "label": "negative", "source": "initial"}],
    },
    {
        "title": "Nuclear Fusion Breakthrough: AI-Optimized Reactors Achieve Net Energy",
        "artifact_type": "news", "author": "Various",
        "url": "",
        "date_published": datetime(2025, 2, 10, tzinfo=timezone.utc),
        "description": "AI-guided plasma control achieves sustained net-positive fusion energy. A key example of AI accelerating solutions to grand challenges, with implications for post-scarcity society.",
        "tags": "fusion,energy,ai-science,breakthrough,post-scarcity",
        "sentiments": [{"score": 0.9, "label": "very_positive", "source": "initial"}],
        "projections": [{"projection_type": "utopian", "confidence": 0.6, "timeframe": "2030-2035", "summary": "AI-accelerated scientific breakthroughs could solve energy, disease, and climate challenges"}],
    },
    {
        "title": "Anthropic Releases Claude 3.5: 'Best model on the market by a clear margin'",
        "artifact_type": "news", "author": "Anthropic",
        "url": "https://www.anthropic.com/news/claude-3-5-sonnet",
        "date_published": datetime(2024, 6, 20, tzinfo=timezone.utc),
        "description": "Anthropic's Claude 3.5 Sonnet outperforms GPT-4 and Gemini across industry benchmarks. Demonstrates rapid capability advancement and intensifying frontier model competition.",
        "tags": "anthropic,claude,capabilities,frontier,benchmarks",
        "sentiments": [{"score": 0.5, "label": "positive", "source": "initial"}],
    },
    {
        "title": "OpenAI Announces Superalignment Team and 20% Compute Commitment",
        "artifact_type": "news", "author": "OpenAI",
        "url": "https://openai.com/blog/introducing-superalignment",
        "date_published": datetime(2023, 7, 5, tzinfo=timezone.utc),
        "description": "OpenAI launches a dedicated team to solve superalignment — aligning superhuman AI systems — and commits 20% of its total compute to safety research.",
        "tags": "superalignment,safety,openai,compute-allocation",
        "sentiments": [{"score": 0.4, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.5, "timeframe": "2023-2028", "summary": "20% compute for superalignment; outcome uncertain but directionally positive"}],
    },
    {
        "title": "EU AI Act Passes: World's First Comprehensive AI Regulation",
        "artifact_type": "news", "author": "European Union",
        "url": "https://artificialintelligenceact.eu/",
        "date_published": datetime(2024, 3, 13, tzinfo=timezone.utc),
        "description": "The EU AI Act enters into force, establishing risk-based regulation for AI systems. While not specifically targeting AGI, sets precedent for frontier AI governance.",
        "tags": "regulation,governance,eu,policy,risk-based",
        "sentiments": [{"score": 0.1, "label": "neutral", "source": "initial"}],
    },
    {
        "title": "DeepSeek R1: Open-Weight Reasoner Challenges Frontier Models",
        "artifact_type": "news", "author": "DeepSeek (China)",
        "url": "",
        "date_published": datetime(2025, 1, 20, tzinfo=timezone.utc),
        "description": "Chinese AI lab DeepSeek releases an open-weight reasoning model that matches or exceeds GPT-4 and Claude on key benchmarks, intensifying the US-China AI race and democratization questions.",
        "tags": "deepseek,china,open-source,race,reasoning",
        "sentiments": [{"score": 0.3, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "accelerationist", "confidence": 0.7, "timeframe": "2025-2027", "summary": "Open-weight models accelerate global AI capabilities; US-China race intensifies"}],
    },
    # ── Research / Papers ──────────────────────────────────────────────────
    {
        "title": "Anthropic's Research on AI Interpretability (Sparse Autoencoders)",
        "artifact_type": "research", "author": "Anthropic",
        "url": "https://transformer-circuits.pub/",
        "date_published": datetime(2024, 5, 21, tzinfo=timezone.utc),
        "description": "Golden Gate Claude and scaling monosemanticity: Anthropic scales sparse autoencoders to decompose activations of a production LLM, finding interpretable features across the model.",
        "tags": "interpretability,mechanistic-interpretability,sae,anthropic",
        "sentiments": [{"score": 0.5, "label": "positive", "source": "initial"}],
    },
    {
        "title": "The Alignment Problem from a Deep Learning Perspective",
        "artifact_type": "research", "author": "Richard Ngo, Lawrence Chan, et al.",
        "url": "https://arxiv.org/abs/2209.00626",
        "date_published": datetime(2022, 9, 1, tzinfo=timezone.utc),
        "description": "Comprehensive survey of the alignment problem through the lens of deep learning. Covers goal misgeneralization, deceptive alignment, and the challenges of specification and robustness.",
        "tags": "alignment,survey,deep-learning,goal-misgeneralization,deception",
        "sentiments": [{"score": -0.2, "label": "negative", "source": "initial"}],
    },
    {
        "title": "Risks from Learned Optimization in Advanced Machine Learning Systems",
        "artifact_type": "research", "author": "Evan Hubinger, Chris van Merwijk, et al.",
        "url": "https://arxiv.org/abs/1906.01820",
        "date_published": datetime(2019, 6, 5, tzinfo=timezone.utc),
        "description": "Introduces the concept of mesa-optimization: learned optimization algorithms within neural networks that may pursue their own goals, posing risks of deceptive alignment and goal drift.",
        "tags": "mesa-optimization,deceptive-alignment,inner-alignment,risks",
        "sentiments": [{"score": -0.4, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "cautionary", "confidence": 0.75, "timeframe": "2025-2040", "summary": "Mesa-optimization could cause AI systems to pursue proxy goals that diverge from intended objectives"}],
    },
    {
        "title": "Discovering Latent Knowledge in Language Models Without Supervision",
        "artifact_type": "research", "author": "Collin Burns, Haotian Ye, Dan Klein, et al.",
        "url": "https://arxiv.org/abs/2212.03827",
        "date_published": datetime(2022, 12, 7, tzinfo=timezone.utc),
        "description": "Demonstrates that contrast-consistent search can extract truthful knowledge from activations of pretrained language models without using labels, enabling 'eliciting latent knowledge' (ELK).",
        "tags": "elk,knowledge,truthfulness,activations,interpretability",
        "sentiments": [{"score": 0.4, "label": "positive", "source": "initial"}],
    },
    # ── Projections ─────────────────────────────────────────────────────────
    {
        "title": "Metaculus AGI Timeline Prediction: Community Forecast",
        "artifact_type": "projection", "author": "Metaculus",
        "url": "https://www.metaculus.com/questions/",
        "date_published": datetime(2025, 6, 1, tzinfo=timezone.utc),
        "description": "Metaculus community prediction market for AGI arrival. Median forecast has shifted from 2050 (2020) to approximately 2030 (2025), reflecting accelerating AI progress.",
        "tags": "forecast,metaculus,prediction-market,timelines,community",
        "sentiments": [{"score": 0.3, "label": "positive", "source": "initial"}],
        "projections": [{"projection_type": "accelerationist", "confidence": 0.75, "timeframe": "2028-2035", "summary": "Metaculus median AGI forecast ~2030; timelines rapidly shortening as capabilities accelerate"}],
    },
    {
        "title": "Expert Survey 2024: Median AGI Timeline at 2040",
        "artifact_type": "projection", "author": "Various Researchers",
        "url": "",
        "date_published": datetime(2024, 10, 1, tzinfo=timezone.utc),
        "description": "Large-scale survey of AI researchers (including ICML/NeurIPS attendees) finds median prediction for AGI (broadly defined) around 2040, with 50% assigning >10% existential risk from AI.",
        "tags": "survey,experts,timelines,risk,research-community",
        "sentiments": [{"score": -0.2, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "neutral", "confidence": 0.6, "timeframe": "2040", "summary": "Expert median AGI ~2040; significant minority predict much earlier or much later"}],
    },
    {
        "title": "AI Could Replace Majority of Human Economic Activity by 2028-2029",
        "artifact_type": "projection", "author": "Gil Syswerda",
        "url": "",
        "date_published": datetime(2025, 3, 1, tzinfo=timezone.utc),
        "description": "Senior editor Gil Syswerda constructs a timeline predicting AI could replace the majority of human economic activity as early as 2028-2029, with profound implications for post-AGI economic structure.",
        "tags": "economic-activity,automation,employment,timelines,post-work",
        "sentiments": [{"score": 0.0, "label": "neutral", "source": "initial"}],
        "projections": [{"projection_type": "accelerationist", "confidence": 0.6, "timeframe": "2028-2029", "summary": "AI replaces majority of human economic activity by 2028-2029; post-work society imminent"}],
    },
    {
        "title": "Open Philanthropy: AI Risk Landscape Report 2025",
        "artifact_type": "projection", "author": "Open Philanthropy",
        "url": "",
        "date_published": datetime(2025, 4, 15, tzinfo=timezone.utc),
        "description": "Comprehensive landscape analysis of AI risk, finding that the probability of existential catastrophe from AI by 2070 is in the range of 5-50%, with the median estimate around 10%.",
        "tags": "existential-risk,xrisk,landscape,philanthropy,probability",
        "sentiments": [{"score": -0.5, "label": "negative", "source": "initial"}],
        "projections": [{"projection_type": "cautionary", "confidence": 0.7, "timeframe": "2025-2070", "summary": "5-50% existential risk from AI by 2070; median ~10%; urgent need for safety investment"}],
    },
]

# Shift the narrative to encompass both techno-optimist and cautionary perspectives,
# creating a balanced knowledge graph.
TITLE = {
    "superintelligence": "Superintelligence: Paths, Dangers, Strategies",
    "singularity": "The Singularity Is Near",
    "life30": "Life 3.0: Being Human in the Age of Artificial Intelligence",
    "human_compatible": "Human Compatible: Artificial Intelligence and the Problem of Control",
    "alignment_problem": "The Alignment Problem: Machine Learning and Human Values",
    "ai2041": "AI 2041: Ten Visions for Our Future",
    "precipice": "The Precipice: Existential Risk and the Future of Humanity",
    "final_invention": "Our Final Invention: Artificial Intelligence and the End of the Human Era",
    "scary_smart": "Scary Smart: The Future of Artificial Intelligence and How You Can Save Our World",
    "genius_makers": "Genius Makers: The Mavericks Who Brought AI to Google, Facebook, and the World",
    "gpt4": "GPT-4 Technical Report",
    "scaling_laws": "Scaling Laws for Neural Language Models",
    "chinchilla": "Training Compute-Optimal Large Language Models (Chinchilla)",
    "constitutional_ai": "Constitutional AI: Harmlessness from AI Feedback",
    "weak_to_strong": "Weak-to-Strong Generalization: Eliciting the Capabilities of Weakly Supervised LLMs",
    "dpo": "Direct Preference Optimization: Your Language Model is Secretly a Reward Model",
    "tot": "Tree of Thoughts: Deliberate Problem Solving with Large Language Models",
    "mech_interp_review": "Mechanistic Interpretability for AI Safety — A Review",
    "agi_ruin": "AGI Ruin: A List of Lethalities",
    "situational_awareness": "Situational Awareness: The Decade Ahead",
    "what_matters": "What Matters Most: AGI and Human Flourishing",
    "bitter_lesson": "The Bitter Lesson",
    "moloch": "Meditations on Moloch",
    "cotra_timelines": "Draft Report on AI Timelines",
    "machines_of_loving_grace": "Machines of Loving Grace: How AI Could Transform the World for the Better",
    "altman_tweet": "Sam Altman: 'AGI will be the most powerful technology humanity has ever built'",
    "musk_tweet": "Elon Musk: 'There is some probability that AI kills humans. I think it's low, but non-trivial — maybe 10-20%'",
    "lecun_tweet": "Yann LeCun: 'AGI is nowhere near imminent — we lack fundamental understanding'",
    "hassabis_tweet": "Demis Hassabis: 'I think we could achieve AGI within the next decade'",
    "karpathy_tweet": "Andrej Karpathy: 'The neural network training process is becoming the new programming'",
    "legg_tweet": "Shane Legg: 'AGI is likely by 2028 — it's the most important event in human history'",
    "hinton_tweet": "Geoffrey Hinton: 'I'm now a pessimist on AI — we're not moving fast enough on safety'",
    "lex_altman": "Lex Fridman Podcast: Sam Altman on AGI, Open Source, and the Future",
    "lex_lecun": "Lex Fridman Podcast: Yann LeCun on AGI, Vision, and the Path Forward",
    "cotra_podcast": "80,000 Hours: Ajeya Cotra on AI Timelines and Bio Anchors",
    "jre_yampolskiy": "Joe Rogan Experience: Roman Yampolskiy on AI Safety and Superintelligence",
    "timelines_debate": "Debate: AGI Timelines — Short vs Long",
    "alphafold": "DeepMind's AlphaFold and AI-Driven Scientific Discovery",
    "pause_letter": "Open Letter: Pause Giant AI Experiments",
    "fusion": "Nuclear Fusion Breakthrough: AI-Optimized Reactors Achieve Net Energy",
    "claude35": "Anthropic Releases Claude 3.5: 'Best model on the market by a clear margin'",
    "superalignment": "OpenAI Announces Superalignment Team and 20% Compute Commitment",
    "eu_act": "EU AI Act Passes: World's First Comprehensive AI Regulation",
    "deepseek": "DeepSeek R1: Open-Weight Reasoner Challenges Frontier Models",
    "anthropic_interp": "Anthropic's Research on AI Interpretability (Sparse Autoencoders)",
    "ngo_alignment": "The Alignment Problem from a Deep Learning Perspective",
    "mesa_optimization": "Risks from Learned Optimization in Advanced Machine Learning Systems",
    "elk": "Discovering Latent Knowledge in Language Models Without Supervision",
    "metaculus": "Metaculus AGI Timeline Prediction: Community Forecast",
    "expert_survey": "Expert Survey 2024: Median AGI Timeline at 2040",
    "syswerda": "AI Could Replace Majority of Human Economic Activity by 2028-2029",
    "open_phil_risk": "Open Philanthropy: AI Risk Landscape Report 2025",
}

RELATIONSHIPS = [
    # books → everything
    (TITLE["superintelligence"], TITLE["agi_ruin"], "supports",
     "Yudkowsky builds on Bostrom's instrumental convergence and orthogonality analysis"),
    (TITLE["superintelligence"], TITLE["alignment_problem"], "references",
     "Christian extensively references Bostrom's framework"),
    (TITLE["superintelligence"], TITLE["human_compatible"], "references",
     "Russell builds on the control problem Bostrom identifies"),
    (TITLE["superintelligence"], TITLE["precipice"], "supports",
     "Ord cites Bostrom in ranking AI as the #1 existential risk"),
    (TITLE["superintelligence"], TITLE["mesa_optimization"], "supports",
     "Mesa-optimization as a concrete mechanism for Bostrom's orthogonality thesis"),
    (TITLE["superintelligence"], TITLE["metaculus"], "references",
     "Bostrom's analysis shapes the community's understanding of AGI timelines"),

    # Singularity / accelerationist cluster
    (TITLE["singularity"], TITLE["what_matters"], "supports",
     "Altman continues Kurzweil's accelerationist vision"),
    (TITLE["singularity"], TITLE["machines_of_loving_grace"], "supports",
     "Amodei's compressed century thesis extends Kurzweil's exponential narrative"),
    (TITLE["singularity"], TITLE["fusion"], "references",
     "Exemplifies the Kurzweilian prediction of technology solving grand challenges"),
    (TITLE["bitter_lesson"], TITLE["scaling_laws"], "supports",
     "Scaling laws provide empirical confirmation of Sutton's thesis"),
    (TITLE["bitter_lesson"], TITLE["gpt4"], "supports",
     "GPT-4 continues the paradigm of general methods + massive compute"),
    (TITLE["bitter_lesson"], TITLE["situational_awareness"], "references",
     "Aschenbrenner applies the bitter lesson to argue for rapid timelines"),
    (TITLE["machines_of_loving_grace"], TITLE["what_matters"], "supports",
     "Both Altman and Amodei share a techno-optimist vision with safety caveats"),
    (TITLE["chinchilla"], TITLE["situational_awareness"], "supports",
     "Scaling compute-optimal models accelerates the capability curve Aschenbrenner describes"),

    # Doom / cautionary cluster
    (TITLE["agi_ruin"], TITLE["alignment_problem"], "supports",
     "Both focus on the severe difficulty of alignment"),
    (TITLE["agi_ruin"], TITLE["final_invention"], "supports",
     "Barrat and Yudkowsky converge on existential risk from unaligned AGI"),
    (TITLE["agi_ruin"], TITLE["moloch"], "supports",
     "Moloch dynamics explain why alignment might not get solved despite awareness"),
    (TITLE["agi_ruin"], TITLE["scary_smart"], "supports",
     "Gawdat and Yudkowsky agree on the inevitability and risk of AGI"),
    (TITLE["agi_ruin"], TITLE["mesa_optimization"], "supports",
     "Mesa-optimization provides a technical mechanism for Yudkowsky's concerns"),
    (TITLE["agi_ruin"], TITLE["jre_yampolskiy"], "supports",
     "Yampolskiy's impossibility results reinforce Yudkowsky's pessimism"),
    (TITLE["mesa_optimization"], TITLE["ngo_alignment"], "supports",
     "Ngo et al. extend mesa-optimization into goal misgeneralization and deceptive alignment"),

    # Timeline / forecast cluster
    (TITLE["situational_awareness"], TITLE["timelines_debate"], "supports",
     "Aschenbrenner's work is a key data point in the short-timeline camp"),
    (TITLE["situational_awareness"], TITLE["cotra_timelines"], "contradicts",
     "Aschenbrenner's 2027-2030 forecast is significantly shorter than Cotra's median 2050"),
    (TITLE["situational_awareness"], TITLE["deepseek"], "references",
     "Open-weight frontier models validate the rapid progress Aschenbrenner describes"),
    (TITLE["cotra_timelines"], TITLE["metaculus"], "supports",
     "Cotra's bio anchors methodology informed early Metaculus forecasting"),
    (TITLE["cotra_timelines"], TITLE["cotra_podcast"], "references",
     "Podcast discussing the bio anchors framework in depth"),
    (TITLE["situational_awareness"], TITLE["syswerda"], "supports",
     "Both predict extremely rapid economic transformation from AI"),
    (TITLE["cotra_timelines"], TITLE["expert_survey"], "contradicts",
     "Expert survey median is later than Cotra's bio anchors estimate"),

    # Altman / optimistic governance cluster
    (TITLE["what_matters"], TITLE["superalignment"], "references",
     "Altman's post references the superalignment initiative"),
    (TITLE["what_matters"], TITLE["lex_altman"], "references",
     "Altman elaborates on these themes in the podcast"),
    (TITLE["what_matters"], TITLE["pause_letter"], "contradicts",
     "Altman's iterative deployment approach contrasts with pause advocates"),

    # Cross-cluster debate connections
    (TITLE["human_compatible"], TITLE["agi_ruin"], "references",
     "Russell and Yudkowsky both identify the control problem as central"),
    (TITLE["human_compatible"], TITLE["what_matters"], "contradicts",
     "Russell's preference-uncertainty approach differs from Altman's capabilities-first framing"),
    (TITLE["moloch"], TITLE["what_matters"], "contradicts",
     "Moloch dynamics suggest Altman's vision may be undermined by competitive pressures"),
    (TITLE["life30"], TITLE["superintelligence"], "references",
     "Tegmark builds on Bostrom's taxonomy of risks and futures"),
    (TITLE["life30"], TITLE["machines_of_loving_grace"], "supports",
     "Both explore positive scenarios for AGI if steered wisely"),
    (TITLE["genius_makers"], TITLE["gpt4"], "references",
     "Metz's history contextualizes the people and institutions behind GPT-4"),
    (TITLE["tot"], TITLE["gpt4"], "builds_upon",
     "ToT enhances LLM reasoning beyond what GPT-4's base capabilities provide"),
    (TITLE["weak_to_strong"], TITLE["superalignment"], "supports",
     "Weak-to-strong generalization is a key superalignment research direction"),
    (TITLE["constitutional_ai"], TITLE["anthropic_interp"], "supports",
     "Both represent Anthropic's multi-pronged approach to safety"),
    (TITLE["dpo"], TITLE["alignment_problem"], "references",
     "DPO addresses the reward modeling challenge described in Christian's book"),
    (TITLE["elk"], TITLE["alignment_problem"], "references",
     "ELK approaches address the scalable oversight dimension of alignment"),
    (TITLE["claude35"], TITLE["anthropic_interp"], "supports",
     "Claude 3.5 capabilities enable new interpretability research at scale"),
    (TITLE["eu_act"], TITLE["pause_letter"], "responds_to",
     "EU AI Act represents a policy response to concerns raised by the pause letter"),
    (TITLE["deepseek"], TITLE["bitter_lesson"], "supports",
     "DeepSeek R1 validates that general methods (scaling + RL at inference) deliver rapid gains"),
    (TITLE["ai2041"], TITLE["life30"], "supports",
     "Both use scenario-based exploration to map possible AI futures"),
    (TITLE["musk_tweet"], TITLE["agi_ruin"], "supports",
     "Both express caution about AGI risk though Musk is less pessimistic"),
    (TITLE["lecun_tweet"], TITLE["situational_awareness"], "contradicts",
     "LeCun's skepticism directly counterposes Aschenbrenner's rapid timelines"),
    (TITLE["hassabis_tweet"], TITLE["lecun_tweet"], "contradicts",
     "Hassabis and LeCun represent the two poles of the timeline debate"),
    (TITLE["hinton_tweet"], TITLE["lecun_tweet"], "contradicts",
     "Hinton's growing pessimism directly opposes LeCun's dismissiveness of AI risk"),
    (TITLE["legg_tweet"], TITLE["hassabis_tweet"], "supports",
     "DeepMind co-founders share similar AGI timeline predictions"),
    (TITLE["open_phil_risk"], TITLE["metaculus"], "references",
     "Open Phil's risk estimates inform the broader forecasting ecosystem"),
    (TITLE["karpathy_tweet"], TITLE["gpt4"], "references",
     "Software 2.0 paradigm at full scale is embodied by GPT-4"),
]


def seed_database(db: Session):
    existing = db.query(Artifact).count()
    if existing > 0:
        return

    for data in SEED_ARTIFACTS:
        sentiments_data = data.pop("sentiments", [])
        projections_data = data.pop("projections", [])

        artifact = Artifact(**data)
        db.add(artifact)
        db.flush()

        for s_data in sentiments_data:
            sentiment = Sentiment(artifact_id=artifact.id, **s_data)
            db.add(sentiment)

        for p_data in projections_data:
            projection = Projection(artifact_id=artifact.id, **p_data)
            db.add(projection)

    db.commit()

    artifacts_map = {a.title: a.id for a in db.query(Artifact).all()}

    for source_title, target_title, rel_type, desc in RELATIONSHIPS:
        src_id = artifacts_map.get(source_title)
        tgt_id = artifacts_map.get(target_title)
        if src_id and tgt_id:
            db.add(Relationship(
                source_id=src_id,
                target_id=tgt_id,
                relationship_type=rel_type,
                description=desc,
            ))

    db.commit()
